### ISSUE TITLE
Standalone build fails with "llvm-build: error: invalid target to enable: 'AArch64' (not in project)"

### ISSUE THREAD

**Issue by s3rvac** [avast-tl/llvm#2]
### Steps to reproduce

```
git clone https://github.com/avast-tl/llvm
cd llvm
mkdir build
cd build
cmake ..
```

### Output

```
-- Constructing LLVMBuild project information
CMake Error at CMakeLists.txt:539 (message):
  Unexpected failure executing llvm-build: Usage: llvm-build [options]



  llvm-build: error: invalid target to enable: 'AArch64' (not in project)


-- Configuring incomplete, errors occurred!
```

### Expected output

```
-- Configuring done
-- Generating done
-- Build files have been written to: llvm/build
```

### Notes

* This is probably caused by the aggressive removal of sources and targets in the `faster-build-2` branch.
* It would be useful to have the standalone build working. For example, one may easily check that LLVM build after custom changes still work. Otherwise, one would have to integrate the changes into RetDec first.

### Configuration

* Latest `master` (c72fb430dad1e64d00d7758b9cee977e0ff8f6cf)
* Arch Linux 64b, GCC 7.2.1

**Comment by noloader** [comment]
Also see [Aarch64 and "llvm-build: error: invalid target to enable: 'Aarch64' (not in project)" ](https://bugs.llvm.org/show_bug.cgi?id=39698) in the LLVM issue tracker.
